[2024-09-27T18:41:47.368+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T18:41:47.493+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.create_share_prices_table scheduled__2024-02-14T00:00:00+00:00 [queued]>
[2024-09-27T18:41:47.549+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.create_share_prices_table scheduled__2024-02-14T00:00:00+00:00 [queued]>
[2024-09-27T18:41:47.560+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-27T18:41:47.639+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_share_prices_table> on 2024-02-14 00:00:00+00:00
[2024-09-27T18:41:47.687+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14362) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T18:41:47.690+0000] {standard_task_runner.py:72} INFO - Started process 14375 to run task
[2024-09-27T18:41:47.700+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_share_prices_with_company_data', 'create_share_prices_table', 'scheduled__2024-02-14T00:00:00+00:00', '--job-id', '1667', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwvyziw60']
[2024-09-27T18:41:47.721+0000] {standard_task_runner.py:105} INFO - Job 1667: Subtask create_share_prices_table
[2024-09-27T18:41:48.029+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_save_share_prices_with_company_data.create_share_prices_table scheduled__2024-02-14T00:00:00+00:00 [running]> on host 13b5797a93ab
[2024-09-27T18:41:48.481+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_save_share_prices_with_company_data' AIRFLOW_CTX_TASK_ID='create_share_prices_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-14T00:00:00+00:00'
[2024-09-27T18:41:48.486+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-27T18:41:48.488+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-27T18:41:48.493+0000] {logging_mixin.py:190} INFO - Current task name:create_share_prices_table state:running start_date:2024-09-27 18:41:47.507329+00:00
[2024-09-27T18:41:48.495+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_save_share_prices_with_company_data and current dag run status:running
[2024-09-27T18:41:48.496+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T18:41:48.527+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T18:41:48.537+0000] {sql.py:509} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS company_share_prices (
            id SERIAL,
            company_id INTEGER NOT NULL,
            date DATE,
            latest_trading_price VARCHAR(50),
            low_price VARCHAR(50),
            high_price VARCHAR(50),
            closing_price VARCHAR(50),
            ycp VARCHAR(50),
            change VARCHAR(10),
            trade VARCHAR(50),
            value VARCHAR(50),
            volume VARCHAR(50),
            PRIMARY KEY(company_id, id),
            FOREIGN KEY(company_id)
                REFERENCES company_list(company_id)
                ON UPDATE CASCADE ON DELETE CASCADE
        );
    , parameters: None
[2024-09-27T18:41:48.557+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 106, in create_share_prices_table
    hook.run(create_table_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "company_list" does not exist

[2024-09-27T18:41:48.622+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-27T18:41:48.623+0000] {logging_mixin.py:190} INFO - Task start:2024-09-27 18:41:47.507329+00:00 end:2024-09-27 18:41:48.621182+00:00 duration:1.113853
[2024-09-27T18:41:48.627+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): create_share_prices_table> dag:<DAG: scrape_and_save_share_prices_with_company_data> dagrun:<DagRun scrape_and_save_share_prices_with_company_data @ 2024-02-14 00:00:00+00:00: scheduled__2024-02-14T00:00:00+00:00, state:running, queued_at: 2024-09-27 18:40:26.674486+00:00. externally triggered: False>
[2024-09-27T18:41:48.629+0000] {logging_mixin.py:190} INFO - Failure caused by relation "company_list" does not exist
[2024-09-27T18:41:48.630+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_save_share_prices_with_company_data, task_id=create_share_prices_table, run_id=scheduled__2024-02-14T00:00:00+00:00, execution_date=20240214T000000, start_date=20240927T184147, end_date=20240927T184148
[2024-09-27T18:41:48.697+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T18:41:48.702+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1667 for task create_share_prices_table (relation "company_list" does not exist
; 14375)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 106, in create_share_prices_table
    hook.run(create_table_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "company_list" does not exist

[2024-09-27T18:41:48.783+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-27T18:41:48.873+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T18:41:48.883+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-27T23:06:23.580+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T23:06:23.624+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.create_share_prices_table scheduled__2024-02-14T00:00:00+00:00 [queued]>
[2024-09-27T23:06:23.645+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.create_share_prices_table scheduled__2024-02-14T00:00:00+00:00 [queued]>
[2024-09-27T23:06:23.646+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-27T23:06:23.712+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_share_prices_table> on 2024-02-14 00:00:00+00:00
[2024-09-27T23:06:23.766+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2844) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T23:06:23.793+0000] {standard_task_runner.py:72} INFO - Started process 2860 to run task
[2024-09-27T23:06:23.784+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_share_prices_with_company_data', 'create_share_prices_table', 'scheduled__2024-02-14T00:00:00+00:00', '--job-id', '3187', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5srl4hwl']
[2024-09-27T23:06:23.803+0000] {standard_task_runner.py:105} INFO - Job 3187: Subtask create_share_prices_table
[2024-09-27T23:06:24.033+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_save_share_prices_with_company_data.create_share_prices_table scheduled__2024-02-14T00:00:00+00:00 [running]> on host 7746de5121f6
[2024-09-27T23:06:24.477+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_save_share_prices_with_company_data' AIRFLOW_CTX_TASK_ID='create_share_prices_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-14T00:00:00+00:00'
[2024-09-27T23:06:24.486+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-27T23:06:24.490+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-27T23:06:24.491+0000] {logging_mixin.py:190} INFO - Current task name:create_share_prices_table state:running start_date:2024-09-27 23:06:23.625825+00:00
[2024-09-27T23:06:24.492+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_save_share_prices_with_company_data and current dag run status:running
[2024-09-27T23:06:24.496+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T23:06:24.543+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T23:06:24.574+0000] {sql.py:509} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS company_share_prices (
            id SERIAL,
            company_id INTEGER NOT NULL,
            date DATE,
            latest_trading_price VARCHAR(50),
            low_price VARCHAR(50),
            high_price VARCHAR(50),
            closing_price VARCHAR(50),
            ycp VARCHAR(50),
            change VARCHAR(10),
            trade VARCHAR(50),
            value VARCHAR(50),
            volume VARCHAR(50),
            PRIMARY KEY(company_id, id),
            FOREIGN KEY(company_id)
                REFERENCES company_list(company_id)
                ON UPDATE CASCADE ON DELETE CASCADE
        );
    , parameters: None
[2024-09-27T23:06:24.600+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-27T23:06:24.665+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T23:06:24.677+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_share_prices_with_company_data, task_id=create_share_prices_table, run_id=scheduled__2024-02-14T00:00:00+00:00, execution_date=20240214T000000, start_date=20240927T230623, end_date=20240927T230624
[2024-09-27T23:06:24.740+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-09-27T23:06:24.766+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-09-27T23:06:24.767+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_save_share_prices_with_company_data queued_at:2024-09-27 23:05:24.403877+00:00
[2024-09-27T23:06:24.768+0000] {logging_mixin.py:190} INFO - Task hostname:7746de5121f6 operator:PythonOperator
[2024-09-27T23:06:24.795+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-27T23:06:24.987+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-27T23:06:25.028+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
